import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { getGraphAccessToken } from "@/lib/sharepoint/graph";
import { ensureInvoiceOriginalFolder, ensureInvoiceSupportingFolder, safeFinanceSharePointPart, uploadInvoiceFile } from "@/lib/sharepoint/finance";

export const runtime="nodejs";export const dynamic="force-dynamic";
const MAX_FILE_BYTES=25*1024*1024;const ALLOWED_TYPES=new Set(["application/pdf","image/jpeg","image/png","image/webp","image/heic","image/heif"]);
function env(name:string){const v=process.env[name]?.trim();if(!v)throw new Error(`Missing environment variable: ${name}`);return v;}
function serviceClient(){return createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false,autoRefreshToken:false}});}
async function requireUser(request:Request){const a=request.headers.get("authorization")??"";const t=a.startsWith("Bearer ")?a.slice(7).trim():"";if(!t)throw new Error("UNAUTHENTICATED");const service=serviceClient();const {data:{user},error}=await service.auth.getUser(t);if(error||!user)throw new Error("UNAUTHENTICATED");return{service,user};}
async function deleteGraphItem(driveId:string,itemId:string){const token=await getGraphAccessToken();const r=await fetch(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(itemId)}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!r.ok&&r.status!==404)throw new Error(`Could not replace the previous SharePoint document (${r.status}).`);}

export async function POST(request:Request){try{
 const {service,user}=await requireUser(request);const form=await request.formData();const file=form.get("file"),submissionId=String(form.get("submissionId")??"").trim(),documentType=String(form.get("documentType")??"invoice").trim();if(!(file instanceof File))return NextResponse.json({error:"Choose an Invoice document."},{status:400});if(!submissionId)return NextResponse.json({error:"Save the Invoice before uploading documents."},{status:400});if(!["invoice","supporting_document"].includes(documentType))return NextResponse.json({error:"Invalid Invoice document type."},{status:400});if(file.size<=0||file.size>MAX_FILE_BYTES)return NextResponse.json({error:"Invoice documents must be 25 MB or smaller."},{status:400});const contentType=file.type||"application/octet-stream";if(!ALLOWED_TYPES.has(contentType))return NextResponse.json({error:"Upload a PDF, JPG, PNG, WEBP, HEIC or HEIF file."},{status:400});
 const inv=await service.from("financial_submissions").select("id,submission_number,submission_type,status,created_by,submitted_by,invoice_date,created_at").eq("id",submissionId).eq("submission_type","invoice").single();if(inv.error||!inv.data)return NextResponse.json({error:"Invoice not found."},{status:404});const invoice=inv.data;
 const rr=await service.from("user_roles").select("role").eq("user_id",user.id).maybeSingle();const role=String(rr.data?.role??"").trim().toLowerCase(),isAdmin=["admin","administrator","site_admin"].includes(role);const rules=await service.from("financial_access_rules").select("can_review_edit,can_approve").eq("active",true).eq("principal_type","user").eq("user_id",user.id).or("applies_to.eq.all,applies_to.eq.invoice");if(rules.error)throw new Error(rules.error.message);const canReview=(rules.data??[]).some(r=>r.can_review_edit||r.can_approve),owns=invoice.created_by===user.id||invoice.submitted_by===user.id;if(!isAdmin&&!canReview&&!owns)return NextResponse.json({error:"You do not have access to this Invoice."},{status:403});if(!["draft","changes_required"].includes(invoice.status)&&!isAdmin)return NextResponse.json({error:"Invoice documents cannot be changed while approval is in progress or after approval."},{status:409});
 const settings=await service.from("financial_settings").select("sharepoint_site_id,sharepoint_drive_id,sharepoint_base_folder").eq("id",true).single();if(settings.error)throw new Error(settings.error.message);if(!settings.data.sharepoint_site_id||!settings.data.sharepoint_drive_id)return NextResponse.json({error:"Finance SharePoint storage has not been connected in Finance Settings."},{status:409});
 const folder=documentType==="invoice"?await ensureInvoiceOriginalFolder({driveId:settings.data.sharepoint_drive_id,baseFolder:settings.data.sharepoint_base_folder||"Expenses & Invoices",submissionNumber:invoice.submission_number,anchorDate:invoice.invoice_date||invoice.created_at}):await ensureInvoiceSupportingFolder({driveId:settings.data.sharepoint_drive_id,baseFolder:settings.data.sharepoint_base_folder||"Expenses & Invoices",submissionNumber:invoice.submission_number,anchorDate:invoice.invoice_date||invoice.created_at});
 const original=safeFinanceSharePointPart(file.name||"invoice.pdf"),dot=original.lastIndexOf("."),stem=dot>0?original.slice(0,dot):original,ext=dot>0?original.slice(dot):"",storedName=`${safeFinanceSharePointPart(stem)}-${Date.now()}${ext}`,content=new Uint8Array(await file.arrayBuffer());const uploaded=await uploadInvoiceFile({driveId:settings.data.sharepoint_drive_id,folderId:folder.id,fileName:storedName,content,contentType});
 const ins=await service.from("financial_attachments").insert({submission_id:submissionId,item_id:null,attachment_type:documentType,file_name:file.name||storedName,content_type:contentType,file_size_bytes:file.size,sharepoint_site_id:settings.data.sharepoint_site_id,sharepoint_drive_id:settings.data.sharepoint_drive_id,sharepoint_item_id:uploaded.id,sharepoint_web_url:uploaded.webUrl??null,uploaded_by:user.id}).select("id,submission_id,item_id,attachment_type,file_name,content_type,file_size_bytes,uploaded_at").single();if(ins.error)throw new Error(`Document uploaded to SharePoint but metadata could not be saved: ${ins.error.message}`);
 if(documentType==="invoice"){const previous=await service.from("financial_attachments").select("id,sharepoint_drive_id,sharepoint_item_id").eq("submission_id",submissionId).eq("attachment_type","invoice").neq("id",ins.data.id);for(const old of previous.data??[]){if(old.sharepoint_drive_id&&old.sharepoint_item_id){try{await deleteGraphItem(old.sharepoint_drive_id,old.sharepoint_item_id)}catch(e){console.warn("Previous Invoice SharePoint cleanup failed",e)}}await service.from("financial_attachments").delete().eq("id",old.id);}}
 await service.from("financial_submission_events").insert({submission_id:submissionId,revision:0,event_type:documentType==="invoice"?"invoice_uploaded":"supporting_document_uploaded",performed_by:user.id,comments:null,metadata:{source:"website",attachment_id:ins.data.id,file_name:file.name,sharepoint_web_url:uploaded.webUrl??null}});return NextResponse.json({attachment:ins.data});
}catch(error){const message=error instanceof Error?error.message:"Invoice document upload failed.";if(message==="UNAUTHENTICATED")return NextResponse.json({error:"You must be signed in."},{status:401});console.error("INVOICE DOCUMENT UPLOAD ERROR:",error);return NextResponse.json({error:message},{status:500});}}
