import { useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { PngSignaturePad } from "@/components/signatures/PngSignaturePad";
import { getApprovalDetail, reviewDocket } from "@/lib/api/approvals";

type Detail={kind:"docket";docket:Record<string,unknown>;project:Record<string,unknown>|null;tower:Record<string,unknown>|null;labour:Array<Record<string,unknown>>;plant:Array<Record<string,unknown>>;delays:Array<Record<string,unknown>>;progress:Array<Record<string,unknown>>;allocations:Array<Record<string,unknown>>;materialEvents:Array<Record<string,unknown>>;transfers:Array<Record<string,unknown>>;clientContentOptions:Array<{key:string;label:string}>};
const clean=(v:unknown)=>String(v??"").trim();
const n=(v:unknown)=>Number(v??0)||0;

export default function DocketApprovalPage(){
 const {docketId}=useLocalSearchParams<{docketId:string}>(); const id=String(docketId||"");
 const [data,setData]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[signature,setSignature]=useState<string|null>(null),[comments,setComments]=useState("");
 const [selectedContent,setSelectedContent]=useState<string[]>([]); const [changeDetails,setChangeDetails]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{setError(null);const p=await getApprovalDetail<Detail>("docket",id);setData(p);setSelectedContent(p.clientContentOptions.map(x=>x.key));}catch(e){setError(e instanceof Error?e.message:"Docket could not be loaded.");}finally{setLoading(false);}},[id]); useEffect(()=>{void load();},[load]);
 const requests=useMemo(()=>Object.entries(changeDetails).map(([category,detail])=>({category,detail:detail.trim()})).filter(x=>x.detail),[changeDetails]);
 async function submit(action:"approve"|"request_changes"){
  if(action==="approve"&&!signature){Alert.alert("Signature required","Sign before approving the Daily Docket.");return;} if(action==="approve"&&selectedContent.length===0){Alert.alert("Client content required","Select at least one section to include in the client Daily Docket.");return;} if(action==="request_changes"&&requests.length===0&&!comments.trim()){Alert.alert("Changes required","Select a section and enter the required correction.");return;}
  setBusy(action);setError(null);try{await reviewDocket({docketId:id,action,comments:comments.trim(),changeRequests:requests,reviewerSignatureDataUrl:signature||undefined,clientContentKeys:selectedContent});Alert.alert("Saved",action==="approve"?"Daily Docket approved and sent into the existing client approval workflow.":"Daily Docket returned for changes.");await load();}catch(e){setError(e instanceof Error?e.message:"Review failed.");}finally{setBusy(null);}
 }
 if(loading)return<SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:80}}/></SafeAreaView>; if(!data)return<SafeAreaView style={s.safe}><Text style={s.error}>{error||"Not found"}</Text></SafeAreaView>;
 const d=data.docket;return<SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>BC DAILY DOCKET REVIEW</Text><Text style={s.heading}>{clean(data.tower?.name)||"Tower"}</Text><Text style={s.muted}>{[clean(data.project?.project_number),clean(data.project?.name),clean(d.docket_date),`R${String(Number(d.approval_revision??1)).padStart(2,"0")}`].filter(Boolean).join(" · ")}</Text>
 <Card title="Site Summary"><Text style={s.body}>{clean(d.daily_site_summary)||"No site summary."}</Text>{Array.isArray(d.rfi_references)&&d.rfi_references.length?<Text style={s.muted}>RFIs: {(d.rfi_references as unknown[]).map(clean).join(", ")}</Text>:null}</Card>
 <Card title="Workforce"><Text style={s.metric}>{data.labour.length} personnel · {n(d.raw_manhours).toFixed(2)} raw MH · {n(d.production_manhours).toFixed(2)} production MH</Text>{data.labour.slice(0,30).map((r,i)=><Text key={i} style={s.row}>{clean(r.worker_name)||"Worker"} · {clean(r.total_hours)||"0"} h</Text>)}</Card>
 <Card title="Progress">{data.progress.length?data.progress.map((r,i)=><Text key={i} style={s.row}>{clean(r.section_label||r.section_code)||`Row ${i+1}`} · Assembly {clean(r.assembly_today||r.assembled_qty||0)} · Erection {clean(r.erection_today||r.erected_qty||0)}</Text>):<Text style={s.muted}>No progress rows.</Text>}</Card>
 <Card title="Plant / Delays"><Text style={s.metric}>{data.plant.length} plant items · {data.delays.length} delays</Text>{data.delays.map((r,i)=><Text key={i} style={s.row}>{clean(r.delay_type)||"Delay"} · {n(r.delay_hours).toFixed(2)} h · {clean(r.delay_reason)}</Text>)}</Card>
 <Card title="Materials"><Text style={s.metric}>{data.materialEvents.length} events · {data.transfers.length} bundle transfers</Text>{data.materialEvents.map((r,i)=><Text key={i} style={s.row}>{clean(r.event_type).replaceAll("_"," ")} · {clean(r.affected_section||r.notes)}</Text>)}</Card>
 <Card title="Client Docket Sections"><Text style={s.muted}>These selections are passed to the existing controlled PDF/client workflow.</Text><View style={s.chips}>{data.clientContentOptions.map(opt=>{const on=selectedContent.includes(opt.key);return<Pressable key={opt.key} onPress={()=>setSelectedContent(c=>on?c.filter(x=>x!==opt.key):[...c,opt.key])} style={[s.chip,on&&s.chipOn]}><Text style={[s.chipText,on&&s.chipTextOn]}>{opt.label}</Text></Pressable>})}</View></Card>
 <Card title="Request Changes"><Text style={s.muted}>Enter a correction against any section that needs work.</Text>{data.clientContentOptions.map(opt=><View key={opt.key} style={{gap:5}}><Text style={s.label}>{opt.label}</Text><TextInput value={changeDetails[opt.label]??""} onChangeText={v=>setChangeDetails(c=>({...c,[opt.label]:v}))} placeholder="Leave blank if no change required" style={s.input}/></View>)}<TextInput value={comments} onChangeText={setComments} placeholder="General reviewer comments" multiline style={[s.input,{minHeight:80,textAlignVertical:"top"}]}/><Pressable disabled={!!busy} onPress={()=>void submit("request_changes")} style={[s.button,s.warn]}><Text style={s.buttonText}>{busy==="request_changes"?"Sending…":"Request Changes"}</Text></Pressable></Card>
 <Card title="Approve"><Text style={s.muted}>A BC reviewer signature is required by the existing review API.</Text><PngSignaturePad onChange={setSignature} disabled={!!busy}/>{error?<Text style={s.errorInline}>{error}</Text>:null}<Pressable disabled={!!busy} onPress={()=>void submit("approve")} style={[s.button,s.good]}><Text style={s.buttonText}>{busy==="approve"?"Approving…":"Approve Daily Docket"}</Text></Pressable></Card>
 </ScrollView></SafeAreaView>
}
function Card({title,children}:{title:string;children:React.ReactNode}){return<View style={s.card}><Text style={s.cardTitle}>{title}</Text>{children}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f8fafc"},content:{padding:18,gap:14},eyebrow:{fontSize:12,fontWeight:"900",letterSpacing:1.2,color:"#2563eb"},heading:{fontSize:29,fontWeight:"900",color:"#0f172a"},muted:{color:"#64748b",lineHeight:20},body:{color:"#334155",lineHeight:22},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:18,padding:16,gap:10},cardTitle:{fontSize:17,fontWeight:"900",color:"#0f172a"},metric:{fontWeight:"900",color:"#0f172a"},row:{paddingVertical:5,color:"#475569"},chips:{flexDirection:"row",flexWrap:"wrap",gap:7},chip:{borderWidth:1,borderColor:"#cbd5e1",paddingHorizontal:10,paddingVertical:8,borderRadius:99},chipOn:{backgroundColor:"#dbeafe",borderColor:"#60a5fa"},chipText:{fontWeight:"700",color:"#475569",fontSize:12},chipTextOn:{color:"#1d4ed8"},label:{fontWeight:"800",color:"#334155",fontSize:12},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:11,padding:11,backgroundColor:"#fff"},button:{borderRadius:12,padding:14,alignItems:"center"},warn:{backgroundColor:"#d97706"},good:{backgroundColor:"#047857"},buttonText:{color:"#fff",fontWeight:"900"},error:{margin:18,padding:12,color:"#be123c"},errorInline:{color:"#be123c",fontWeight:"700"}});
