import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { docketEmailShell, sendDailyDocketEmail } from "@/lib/email/daily-dockets";

export const runtime="nodejs";export const dynamic="force-dynamic";
function env(name:string){const v=process.env[name]?.trim();if(!v)throw new Error(`Missing environment variable: ${name}`);return v;}
function serviceClient(){return createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false,autoRefreshToken:false}});}
async function requireUser(request:Request){const a=request.headers.get("authorization")??"";const t=a.startsWith("Bearer ")?a.slice(7).trim():"";if(!t)throw new Error("UNAUTHENTICATED");const service=serviceClient();const {data:{user},error}=await service.auth.getUser(t);if(error||!user)throw new Error("UNAUTHENTICATED");return{service,user};}
function baseUrl(){let v=(process.env.NEXT_PUBLIC_APP_URL||process.env.APP_URL||process.env.VERCEL_PROJECT_PRODUCTION_URL||"").trim();if(v&&!/^https?:\/\//i.test(v))v=`https://${v}`;if(!v)throw new Error("Set NEXT_PUBLIC_APP_URL for TTTracker.");return v.replace(/\/$/,"");}
function money(value:unknown){return new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(value??0)||0);}
function esc(value:unknown){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function dateLabel(value?:string|null){if(!value)return"—";const d=new Date(`${value}T00:00:00Z`);if(Number.isNaN(d.getTime()))return value;return new Intl.DateTimeFormat("en-AU",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(d);}
async function roleFor(service:ReturnType<typeof serviceClient>,userId:string){const {data}=await service.from("user_roles").select("role").eq("user_id",userId).maybeSingle();return String(data?.role??"").trim().toLowerCase();}

export async function POST(request:Request){try{
  const body=await request.json() as {submissionId?:string};const submissionId=String(body.submissionId??"").trim();if(!submissionId)return NextResponse.json({error:"Invoice ID is required."},{status:400});
  const {service,user}=await requireUser(request);
  const inv=await service.from("financial_submissions").select("id,submission_number,submission_type,status,revision,created_by,submitted_by,project_id,supplier_name,supplier_abn,supplier_email,invoice_number,invoice_date,received_date,due_date,payment_terms_days,purchase_order_number,description,subtotal_ex_gst,gst_amount,total_amount").eq("id",submissionId).single();
  if(inv.error||!inv.data)return NextResponse.json({error:"Invoice not found."},{status:404});const invoice=inv.data;if(invoice.submission_type!=="invoice")return NextResponse.json({error:"This is not an Invoice."},{status:400});if(!["draft","submitted","changes_required"].includes(invoice.status))return NextResponse.json({error:"This Invoice cannot be submitted from its current status."},{status:409});
  const role=await roleFor(service,user.id),isAdmin=["admin","administrator","site_admin"].includes(role);const ownRules=await service.from("financial_access_rules").select("can_review_edit,can_approve").eq("active",true).eq("principal_type","user").eq("user_id",user.id).or("applies_to.eq.all,applies_to.eq.invoice");if(ownRules.error)throw new Error(ownRules.error.message);const canReview=(ownRules.data??[]).some(r=>r.can_review_edit||r.can_approve);const owns=invoice.created_by===user.id||invoice.submitted_by===user.id;if(!owns&&!canReview&&!isAdmin)return NextResponse.json({error:"You do not have access to submit this Invoice."},{status:403});
  const required:[[unknown,string],[unknown,string],[unknown,string],[unknown,string],[unknown,string]]=[[invoice.supplier_name,"Supplier name"],[invoice.invoice_number,"Supplier invoice number"],[invoice.invoice_date,"Invoice date"],[invoice.due_date,"Due date"],[invoice.description,"Description / purpose"]];const missing=required.filter(([v])=>!String(v??"").trim()).map(([,l])=>l);if(missing.length)return NextResponse.json({error:`Complete the required Invoice fields: ${missing.join(", ")}.`},{status:400});if(Number(invoice.total_amount??0)<=0)return NextResponse.json({error:"Invoice total must be greater than $0."},{status:400});
  const items=await service.from("financial_submission_items").select("id,category_id,description,amount_inc_gst").eq("submission_id",invoice.id).order("sort_order");if(items.error)throw new Error(items.error.message);if(!items.data?.length)return NextResponse.json({error:"Add at least one cost allocation."},{status:400});if(items.data.some(i=>!i.category_id||!String(i.description??"").trim()))return NextResponse.json({error:"Every allocation needs a category and description."},{status:400});const allocationTotal=items.data.reduce((s,i)=>s+(Number(i.amount_inc_gst??0)||0),0),invoiceTotal=Number(invoice.total_amount??0)||0;if(Math.abs(allocationTotal-invoiceTotal)>0.02)return NextResponse.json({error:`Cost allocations total ${money(allocationTotal)} but the Invoice total is ${money(invoiceTotal)}. Balance the allocations before submitting.`},{status:400});
  const originals=await service.from("financial_attachments").select("id").eq("submission_id",invoice.id).eq("attachment_type","invoice");if(originals.error)throw new Error(originals.error.message);if(!originals.data?.length)return NextResponse.json({error:"Upload the original supplier Invoice before submitting for approval."},{status:400});
  const rr=await service.from("financial_access_rules").select("user_id,receives_email,receives_in_app,can_review_edit,can_approve").eq("active",true).eq("principal_type","user").not("user_id","is",null).or("applies_to.eq.all,applies_to.eq.invoice");if(rr.error)throw new Error(rr.error.message);const active=(rr.data??[]).filter(r=>r.can_review_edit||r.can_approve),reviewerIds=[...new Set(active.map(r=>String(r.user_id??"").trim()).filter(Boolean))];if(!reviewerIds.length)return NextResponse.json({error:"No Invoice reviewers are configured in Finance Settings."},{status:400});
  const old=Math.max(0,Number(invoice.revision??0)||0),revision=invoice.status==="changes_required"?old+1:Math.max(old,1),now=new Date().toISOString();const up=await service.from("financial_submissions").update({status:"submitted",submitted_by:user.id,submitted_at:now,revision,changes_required_reason:null,changes_requested_at:null}).eq("id",invoice.id).in("status",["draft","submitted","changes_required"]).select("id,total_amount").maybeSingle();if(up.error)throw new Error(up.error.message);if(!up.data)return NextResponse.json({error:"The Invoice changed before submission. Refresh and try again."},{status:409});
  const updatedInvoice=up.data;
  const ap=await service.from("financial_approvals").insert({submission_id:invoice.id,revision,status:"pending",created_at:now});if(ap.error)throw new Error(ap.error.message);await service.from("financial_submission_events").insert({submission_id:invoice.id,revision,event_type:invoice.status==="changes_required"?"resubmitted":"submitted",performed_by:user.id,comments:null,metadata:{source:"website",submission_type:"invoice",previous_status:invoice.status,reviewer_user_ids:reviewerIds}});
  const settings=await service.from("financial_settings").select("approval_email_enabled,approval_in_app_enabled,approval_push_enabled").eq("id",true).maybeSingle();
  if(settings.data?.approval_in_app_enabled!==false){const rows=reviewerIds.filter(id=>active.some(r=>r.user_id===id&&r.receives_in_app)).map(id=>({user_id:id,event_type:"finance_invoice_submitted",title:`Invoice ${invoice.submission_number}`,message:`${invoice.supplier_name} · ${money(updatedInvoice.total_amount)} · Due ${dateLabel(invoice.due_date)}`,severity:"info",read_at:null,archived_at:null,project_id:invoice.project_id??null,fleet_job_id:null,asset_type:null,asset_id:null,docket_id:null,action_route:"/expenses/invoices",action_params:{submission_id:invoice.id,open:invoice.id,submission_type:"invoice"},source_table:"financial_submissions",source_record_id:invoice.id,created_at:now}));if(rows.length){const n=await service.from("user_notifications").insert(rows);if(n.error)console.error("Invoice in-app notification failed",n.error);}}
  let warning:string|null=null;if(settings.data?.approval_email_enabled!==false){const ids=reviewerIds.filter(id=>active.some(r=>r.user_id===id&&r.receives_email)),emails:string[]=[];for(const id of ids){const u=await service.auth.admin.getUserById(id);if(u.data.user?.email)emails.push(u.data.user.email);}const to=[...new Set(emails)];if(to.length){try{const url=`${baseUrl()}/expenses/invoices?open=${encodeURIComponent(invoice.id)}`;await sendDailyDocketEmail({to,subject:`Invoice approval required · ${invoice.submission_number} · Due ${dateLabel(invoice.due_date)}`,html:docketEmailShell("Supplier Invoice awaiting approval",`<p>A supplier Invoice has been submitted and is ready for review.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:20px 0;border-collapse:collapse;"><tr><td style="padding:8px 0;color:#64748b;width:160px;">TTTracker ref</td><td style="padding:8px 0;font-weight:600;">${esc(invoice.submission_number)}</td></tr><tr><td style="padding:8px 0;color:#64748b;">Supplier</td><td style="padding:8px 0;font-weight:600;">${esc(invoice.supplier_name)}</td></tr><tr><td style="padding:8px 0;color:#64748b;">Supplier invoice</td><td style="padding:8px 0;font-weight:600;">${esc(invoice.invoice_number)}</td></tr><tr><td style="padding:8px 0;color:#64748b;">Amount</td><td style="padding:8px 0;font-weight:600;">${esc(money(updatedInvoice.total_amount))}</td></tr><tr><td style="padding:8px 0;color:#64748b;">Due</td><td style="padding:8px 0;font-weight:600;">${esc(dateLabel(invoice.due_date))}</td></tr></table><p style="margin:24px 0;"><a href="${url}" style="display:inline-block;background:#0f172a;color:#fff;text-decoration:none;font-weight:700;padding:12px 20px;border-radius:10px;">Review Invoice</a></p>`)})}catch(e){console.error("Invoice reviewer email failed",e);warning="The Invoice was submitted, but reviewer email could not be sent.";}}}
  return NextResponse.json({success:true,status:"submitted",revision,reviewers:reviewerIds.length,warning,pushEnabled:settings.data?.approval_push_enabled!==false});
}catch(error){const message=error instanceof Error?error.message:"The Invoice could not be submitted.";if(message==="UNAUTHENTICATED")return NextResponse.json({error:"You must be signed in."},{status:401});console.error("INVOICE SUBMIT ERROR:",error);return NextResponse.json({error:message},{status:500});}}
