import type { SupabaseClient } from "@supabase/supabase-js";
import { loadSystemPdfBranding } from "@/lib/branding/server";
import { generateApprovedInvoicePdf } from "@/lib/finance/invoice-pdf";
import { ensureInvoiceFolder, safeFinanceSharePointPart, uploadInvoiceFile } from "@/lib/sharepoint/finance";

type InvoiceSubmission={id:string;submission_number:string;revision:number|null;created_by:string;submitted_by:string|null;project_id:string|null;supplier_name:string|null;supplier_abn:string|null;supplier_contact_name:string|null;supplier_email:string|null;invoice_number:string|null;invoice_date:string|null;received_date:string|null;due_date:string|null;payment_terms_days:number|null;purchase_order_number:string|null;subcontract_number:string|null;work_order_reference:string|null;description:string|null;notes:string|null;subtotal_ex_gst:number|string|null;gst_amount:number|string|null;total_amount:number|string|null;submitted_at:string|null;created_at:string;};

export async function publishApprovedInvoice({service,submission,approvedByUserId,approvedByName,approvedByEmail,approvedAt}:{service:SupabaseClient;submission:InvoiceSubmission;approvedByUserId:string;approvedByName:string;approvedByEmail:string|null;approvedAt:string}){
  const {data:settings,error:settingsError}=await service.from("financial_settings").select("sharepoint_site_id,sharepoint_drive_id,sharepoint_base_folder").eq("id",true).single();
  if(settingsError)throw new Error(settingsError.message);if(!settings.sharepoint_site_id||!settings.sharepoint_drive_id)throw new Error("Finance SharePoint storage has not been connected in Finance Settings.");
  const [items,cats,original,project,branding]=await Promise.all([
    service.from("financial_submission_items").select("id,category_id,description,amount_ex_gst,gst_amount,amount_inc_gst,sort_order,project_id,vehicle_asset_id,plant_asset_id,fleet_job_id").eq("submission_id",submission.id).order("sort_order"),
    service.from("financial_categories").select("id,name"),
    service.from("financial_attachments").select("file_name").eq("submission_id",submission.id).eq("attachment_type","invoice").order("uploaded_at"),
    submission.project_id?service.from("projects").select("name,project_number").eq("id",submission.project_id).maybeSingle():Promise.resolve({data:null,error:null}),
    loadSystemPdfBranding(),
  ]);
  if(items.error)throw new Error(items.error.message);if(cats.error)throw new Error(cats.error.message);if(original.error)throw new Error(original.error.message);if(project.error)throw new Error(project.error.message);
  const auth=await service.auth.admin.getUserById(submission.submitted_by||submission.created_by);const submittedBy=String(auth.data.user?.user_metadata?.full_name??auth.data.user?.user_metadata?.name??auth.data.user?.email??"TTTracker User").trim();
  const rows=items.data??[];const catMap=new Map((cats.data??[]).map(r=>[String(r.id),String(r.name)]));
  const vIds=[...new Set(rows.map(r=>String(r.vehicle_asset_id??"")).filter(Boolean))],pIds=[...new Set(rows.map(r=>String(r.plant_asset_id??"")).filter(Boolean))],fIds=[...new Set(rows.map(r=>String(r.fleet_job_id??"")).filter(Boolean))],prIds=[...new Set(rows.map(r=>String(r.project_id??"")).filter(Boolean))];
  const [vs,ps,fs,prs]=await Promise.all([
    vIds.length?service.from("vehicle_assets").select("id,vehicle_id,vehicle_rego,make,model").in("id",vIds):Promise.resolve({data:[],error:null}),
    pIds.length?service.from("plant_assets").select("id,asset_id,rego,make,model").in("id",pIds):Promise.resolve({data:[],error:null}),
    fIds.length?service.from("fleet_jobs").select("id,job_number,asset_label").in("id",fIds):Promise.resolve({data:[],error:null}),
    prIds.length?service.from("projects").select("id,name,project_number").in("id",prIds):Promise.resolve({data:[],error:null}),
  ]);
  for(const r of [vs,ps,fs,prs])if(r.error)throw new Error(r.error.message);
  const vm=new Map((vs.data??[]).map(r=>[String(r.id),r])),pm=new Map((ps.data??[]).map(r=>[String(r.id),r])),fm=new Map((fs.data??[]).map(r=>[String(r.id),r])),prm=new Map((prs.data??[]).map(r=>[String(r.id),r]));
  const projectLabel=project.data?[project.data.project_number,project.data.name].filter(Boolean).join(" - "):"Company / General";
  const pdf=generateApprovedInvoicePdf({submissionNumber:submission.submission_number,revision:Math.max(1,Number(submission.revision??1)||1),supplierName:String(submission.supplier_name??"Supplier"),supplierAbn:submission.supplier_abn,supplierEmail:submission.supplier_email,supplierContactName:submission.supplier_contact_name,supplierInvoiceNumber:String(submission.invoice_number??"—"),invoiceDate:submission.invoice_date,receivedDate:submission.received_date,dueDate:submission.due_date,paymentTermsDays:submission.payment_terms_days,purchaseOrderNumber:submission.purchase_order_number,subcontractNumber:submission.subcontract_number,workOrderReference:submission.work_order_reference,description:submission.description,notes:submission.notes,projectLabel,submittedBy,submittedAt:submission.submitted_at,approvedBy:approvedByName,approvedByEmail,approvedAt,subtotalExGst:Number(submission.subtotal_ex_gst??0)||0,gstAmount:Number(submission.gst_amount??0)||0,totalAmount:Number(submission.total_amount??0)||0,originalInvoiceNames:(original.data??[]).map(r=>r.file_name),allocations:rows.map(item=>{let allocation="Company / General";if(item.fleet_job_id){const r=fm.get(String(item.fleet_job_id));allocation=["Fleet Job",r?.job_number,r?.asset_label].filter(Boolean).join(" · ");}else if(item.vehicle_asset_id){const r=vm.get(String(item.vehicle_asset_id));allocation=["Vehicle",r?.vehicle_id,r?.vehicle_rego,[r?.make,r?.model].filter(Boolean).join(" ")].filter(Boolean).join(" · ");}else if(item.plant_asset_id){const r=pm.get(String(item.plant_asset_id));allocation=["Plant",r?.asset_id,r?.rego,[r?.make,r?.model].filter(Boolean).join(" ")].filter(Boolean).join(" · ");}else if(item.project_id){const r=prm.get(String(item.project_id));allocation=["Project",r?.project_number,r?.name].filter(Boolean).join(" · ");}return{category:item.category_id?catMap.get(String(item.category_id))??"Uncategorised":"Uncategorised",description:item.description,allocation,amountExGst:Number(item.amount_ex_gst??0)||0,gstAmount:Number(item.gst_amount??0)||0,amountIncGst:Number(item.amount_inc_gst??0)||0};}),branding:{logoDataUrl:branding.logoDataUrl,companyName:branding.companyName}});
  const folder=await ensureInvoiceFolder({driveId:settings.sharepoint_drive_id,baseFolder:settings.sharepoint_base_folder||"Expenses & Invoices",submissionNumber:submission.submission_number,anchorDate:submission.invoice_date||submission.created_at});
  const revision=Math.max(1,Number(submission.revision??1)||1);const fileName=safeFinanceSharePointPart(`${submission.submission_number}-R${String(revision).padStart(2,"0")}-Approved.pdf`);
  const uploaded=await uploadInvoiceFile({driveId:settings.sharepoint_drive_id,folderId:folder.id,fileName,content:pdf,contentType:"application/pdf"});
  const existing=await service.from("financial_attachments").select("id").eq("submission_id",submission.id).eq("attachment_type","supporting_document").eq("file_name",fileName).maybeSingle();if(existing.error)throw new Error(existing.error.message);
  const meta={submission_id:submission.id,item_id:null,attachment_type:"supporting_document",file_name:fileName,content_type:"application/pdf",file_size_bytes:pdf.byteLength,sharepoint_site_id:settings.sharepoint_site_id,sharepoint_drive_id:settings.sharepoint_drive_id,sharepoint_item_id:uploaded.id,sharepoint_web_url:uploaded.webUrl??null,uploaded_by:approvedByUserId};
  const write=existing.data?.id?await service.from("financial_attachments").update(meta).eq("id",existing.data.id):await service.from("financial_attachments").insert(meta);if(write.error)throw new Error(write.error.message);
  return{fileName,folderId:folder.id,itemId:uploaded.id,webUrl:uploaded.webUrl??null,driveId:settings.sharepoint_drive_id,siteId:settings.sharepoint_site_id};
}
