import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { getGraphAccessToken } from "@/lib/sharepoint/graph";
export const runtime="nodejs";export const dynamic="force-dynamic";
type Context={params:Promise<{attachmentId:string}>};
function env(name:string){const v=process.env[name]?.trim();if(!v)throw new Error(`Missing environment variable: ${name}`);return v;}
function serviceClient(){return createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false,autoRefreshToken:false}});}
async function requireUser(request:Request){const a=request.headers.get("authorization")??"";const t=a.startsWith("Bearer ")?a.slice(7).trim():"";if(!t)throw new Error("UNAUTHENTICATED");const service=serviceClient();const {data:{user},error}=await service.auth.getUser(t);if(error||!user)throw new Error("UNAUTHENTICATED");return{service,user};}
export async function DELETE(request:Request,context:Context){try{const {attachmentId}=await context.params;const {service,user}=await requireUser(request);const a=await service.from("financial_attachments").select("id,submission_id,attachment_type,file_name,sharepoint_drive_id,sharepoint_item_id").eq("id",attachmentId).single();if(a.error||!a.data)return NextResponse.json({error:"Invoice document not found."},{status:404});if(!["invoice","supporting_document"].includes(a.data.attachment_type))return NextResponse.json({error:"This attachment is not an editable Invoice document."},{status:400});const q=await service.from("financial_submissions").select("id,submission_type,status,created_by,submitted_by").eq("id",a.data.submission_id).eq("submission_type","invoice").single();if(q.error||!q.data)return NextResponse.json({error:"Invoice not found."},{status:404});const roleRow=await service.from("user_roles").select("role").eq("user_id",user.id).maybeSingle();const role=String(roleRow.data?.role??"").trim().toLowerCase(),isAdmin=["admin","administrator","site_admin"].includes(role);const rules=await service.from("financial_access_rules").select("can_review_edit,can_approve").eq("active",true).eq("principal_type","user").eq("user_id",user.id).or("applies_to.eq.all,applies_to.eq.invoice");const canReview=(rules.data??[]).some(r=>r.can_review_edit||r.can_approve),owns=q.data.created_by===user.id||q.data.submitted_by===user.id;if(!isAdmin&&!canReview&&!owns)return NextResponse.json({error:"You do not have access to this Invoice."},{status:403});if(!["draft","changes_required"].includes(q.data.status)&&!isAdmin)return NextResponse.json({error:"Invoice documents cannot be removed after submission."},{status:409});if(a.data.sharepoint_drive_id&&a.data.sharepoint_item_id){const token=await getGraphAccessToken();const r=await fetch(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(a.data.sharepoint_drive_id)}/items/${encodeURIComponent(a.data.sharepoint_item_id)}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!r.ok&&r.status!==404)throw new Error(`SharePoint document could not be deleted (${r.status}): ${await r.text()}`);}const d=await service.from("financial_attachments").delete().eq("id",a.data.id);if(d.error)throw new Error(d.error.message);await service.from("financial_submission_events").insert({submission_id:q.data.id,revision:0,event_type:"invoice_document_removed",performed_by:user.id,comments:null,metadata:{source:"website",file_name:a.data.file_name,attachment_id:a.data.id}});return NextResponse.json({success:true,deleted:true});}catch(error){const message=error instanceof Error?error.message:"Invoice document could not be removed.";if(message==="UNAUTHENTICATED")return NextResponse.json({error:"You must be signed in."},{status:401});console.error("INVOICE DOCUMENT DELETE ERROR:",error);return NextResponse.json({error:message},{status:500});}}
