import * as DocumentPicker from "expo-document-picker";
import * as ImagePicker from "expo-image-picker";
import { router, type Href } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { getMyFinance, saveFinanceDraft, submitExpenseClaim, submitInvoice, uploadExpenseReceipt, uploadInvoiceDocument, type PickedFinanceFile } from "@/lib/api/finance";
import type { FinancePayload } from "@/types/finance";

type Kind="expense"|"invoice";
type Line={description:string;categoryId:string;expenseDate:string;amountIncGst:string;gstAmount:string;notes:string;projectId:string;receipt:PickedFinanceFile|null};
const today=()=>new Date().toISOString().slice(0,10);
const emptyLine=():Line=>({description:"",categoryId:"",expenseDate:today(),amountIncGst:"",gstAmount:"",notes:"",projectId:"",receipt:null});
const clean=(v:unknown)=>String(v??"").trim();

export function FinanceDraftForm({kind}:{kind:Kind}){
 const [ref,setRef]=useState<FinancePayload|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [projectId,setProjectId]=useState(""),[description,setDescription]=useState(""),[notes,setNotes]=useState("");
 const [supplierName,setSupplierName]=useState(""),[supplierAbn,setSupplierAbn]=useState(""),[invoiceNumber,setInvoiceNumber]=useState(""),[invoiceDate,setInvoiceDate]=useState(today()),[receivedDate,setReceivedDate]=useState(today()),[dueDate,setDueDate]=useState(""),[po,setPo]=useState("");
 const [lines,setLines]=useState<Line[]>([emptyLine()]); const [invoiceFile,setInvoiceFile]=useState<PickedFinanceFile|null>(null);
 useEffect(()=>{void getMyFinance(kind==="expense"?"expense_claim":"invoice").then(setRef).catch(e=>Alert.alert("Could not load Finance",e instanceof Error?e.message:"Please try again.")).finally(()=>setLoading(false));},[kind]);
 const total=useMemo(()=>lines.reduce((s,r)=>s+(Number(r.amountIncGst)||0),0),[lines]);
 function patchLine(i:number,p:Partial<Line>){setLines(c=>c.map((r,x)=>x===i?{...r,...p}:r));}
 async function pickFile(source:"camera"|"file"):Promise<PickedFinanceFile|null>{
   if(source==="camera"){const result=await ImagePicker.launchCameraAsync({mediaTypes:["images"],quality:0.8});if(result.canceled)return null;const a=result.assets[0];return{uri:a.uri,name:a.fileName||`photo-${Date.now()}.jpg`,mimeType:a.mimeType||"image/jpeg"};}
   const result=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,multiple:false});if(result.canceled)return null;const a=result.assets[0];return{uri:a.uri,name:a.name||`document-${Date.now()}`,mimeType:a.mimeType||"application/octet-stream"};
 }
 async function save(submit:boolean){
   if(lines.length===0||lines.some(r=>!r.description.trim()||!(Number(r.amountIncGst)>=0))){Alert.alert("Check items","Each item needs a description and amount.");return;}
   if(kind==="invoice"&&!supplierName.trim()){Alert.alert("Supplier required","Enter the supplier name.");return;}
   setSaving(true);try{
    const result=await saveFinanceDraft({type:kind==="expense"?"expense_claim":"invoice",projectId,description,notes,supplierName,supplierAbn,invoiceNumber,invoiceDate,receivedDate,dueDate,purchaseOrderNumber:po,allocations:lines.map(r=>({categoryId:r.categoryId,expenseDate:r.expenseDate,description:r.description,amountIncGst:Number(r.amountIncGst)||0,gstAmount:Number(r.gstAmount)||0,notes:r.notes,projectId:r.projectId||projectId}))});
    if(kind==="expense"){
      for(let i=0;i<result.items.length;i++){const file=lines[i]?.receipt;if(file)await uploadExpenseReceipt({submissionId:result.submissionId,itemId:result.items[i].id,file});}
      if(submit)await submitExpenseClaim(result.submissionId);
      Alert.alert(submit?"Submitted":"Draft saved",submit?"Expense Claim submitted for review.":"Expense Claim saved as a draft.",[{text:"OK",onPress:()=>router.replace("/(drawer)/expenses" as Href)}]);
    }else{
      if(invoiceFile)await uploadInvoiceDocument({submissionId:result.submissionId,file:invoiceFile,documentType:"invoice"});
      if(submit)await submitInvoice(result.submissionId);
      Alert.alert(submit?"Submitted":"Draft saved",submit?"Invoice submitted for review.":"Invoice saved as a draft.",[{text:"OK",onPress:()=>router.replace("/(drawer)/invoices" as Href)}]);
    }
   }catch(e){Alert.alert("Could not save",e instanceof Error?e.message:"Please try again.");}finally{setSaving(false);}
 }
 if(loading)return<SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:80}}/></SafeAreaView>;
 return<SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>FINANCE</Text><Text style={s.heading}>{kind==="expense"?"New Expense Claim":"New Invoice"}</Text><Text style={s.muted}>This writes to the same Finance register and approval workflow as TTTracker web.</Text>
 <Card title="General"><Label text="Project"><SelectLike value={projectId} options={(ref?.projects??[]).map(p=>({value:p.id,label:[p.project_number,p.name].filter(Boolean).join(" · ")}))} onChange={setProjectId}/></Label>{kind==="invoice"?<><Label text="Supplier"><TextInput style={s.input} value={supplierName} onChangeText={setSupplierName}/></Label><Label text="Supplier ABN"><TextInput style={s.input} value={supplierAbn} onChangeText={setSupplierAbn}/></Label><Label text="Invoice Number"><TextInput style={s.input} value={invoiceNumber} onChangeText={setInvoiceNumber}/></Label><View style={s.two}><Label text="Invoice Date"><TextInput style={s.input} value={invoiceDate} onChangeText={setInvoiceDate} placeholder="YYYY-MM-DD"/></Label><Label text="Due Date"><TextInput style={s.input} value={dueDate} onChangeText={setDueDate} placeholder="YYYY-MM-DD"/></Label></View><Label text="Purchase Order"><TextInput style={s.input} value={po} onChangeText={setPo}/></Label><View style={s.fileRow}><Text style={s.label}>Original Invoice</Text><Pressable style={s.fileButton} onPress={async()=>setInvoiceFile(await pickFile("file"))}><Text style={s.fileButtonText}>{invoiceFile?invoiceFile.name:"Choose Invoice"}</Text></Pressable></View></>:null}<Label text="Description"><TextInput style={s.input} value={description} onChangeText={setDescription}/></Label><Label text="Notes"><TextInput style={[s.input,{minHeight:80,textAlignVertical:"top"}]} multiline value={notes} onChangeText={setNotes}/></Label></Card>
 <Card title={kind==="expense"?"Expense Items":"Cost Allocations"}>{lines.map((r,i)=><View key={i} style={s.line}><Text style={s.lineTitle}>Item {i+1}</Text><Label text="Description"><TextInput style={s.input} value={r.description} onChangeText={v=>patchLine(i,{description:v})}/></Label><Label text="Category"><SelectLike value={r.categoryId} options={(ref?.categories??[]).filter(c=>c.active).map(c=>({value:c.id,label:c.name}))} onChange={v=>patchLine(i,{categoryId:v})}/></Label><View style={s.two}><Label text="Amount inc GST"><TextInput style={s.input} keyboardType="decimal-pad" value={r.amountIncGst} onChangeText={v=>patchLine(i,{amountIncGst:v})}/></Label><Label text="GST"><TextInput style={s.input} keyboardType="decimal-pad" value={r.gstAmount} onChangeText={v=>patchLine(i,{gstAmount:v})}/></Label></View>{kind==="expense"?<><Label text="Expense Date"><TextInput style={s.input} value={r.expenseDate} onChangeText={v=>patchLine(i,{expenseDate:v})}/></Label><View style={s.fileActions}><Pressable style={s.fileButton} onPress={async()=>patchLine(i,{receipt:await pickFile("camera")})}><Text style={s.fileButtonText}>Take Receipt Photo</Text></Pressable><Pressable style={s.fileButton} onPress={async()=>patchLine(i,{receipt:await pickFile("file")})}><Text style={s.fileButtonText}>Choose Receipt</Text></Pressable></View>{r.receipt?<Text style={s.muted}>Receipt: {r.receipt.name}</Text>:null}</>:null}{lines.length>1?<Pressable onPress={()=>setLines(c=>c.filter((_,x)=>x!==i))}><Text style={s.remove}>Remove item</Text></Pressable>:null}</View>)}<Pressable style={s.add} onPress={()=>setLines(c=>[...c,emptyLine()])}><Text style={s.addText}>+ Add Item</Text></Pressable></Card>
 <View style={s.total}><Text style={s.totalLabel}>Total</Text><Text style={s.totalValue}>{new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(total)}</Text></View><View style={s.actions}><Pressable disabled={saving} style={[s.button,s.secondary]} onPress={()=>void save(false)}><Text style={s.secondaryText}>Save Draft</Text></Pressable><Pressable disabled={saving} style={[s.button,s.primary]} onPress={()=>void save(true)}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Submit</Text>}</Pressable></View>
 </ScrollView></SafeAreaView>
}
function Card({title,children}:{title:string;children:React.ReactNode}){return<View style={s.card}><Text style={s.cardTitle}>{title}</Text>{children}</View>}
function Label({text,children}:{text:string;children:React.ReactNode}){return<View style={{gap:6,flex:1}}><Text style={s.label}>{text}</Text>{children}</View>}
function SelectLike({value,options,onChange}:{value:string;options:Array<{value:string;label:string}>;onChange:(v:string)=>void}){return<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Pressable style={[s.chip,!value&&s.chipOn]} onPress={()=>onChange("")}><Text style={[s.chipText,!value&&s.chipTextOn]}>None</Text></Pressable>{options.map(o=><Pressable key={o.value} style={[s.chip,value===o.value&&s.chipOn]} onPress={()=>onChange(o.value)}><Text style={[s.chipText,value===o.value&&s.chipTextOn]}>{o.label}</Text></Pressable>)}</ScrollView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f8fafc"},content:{padding:18,gap:14,paddingBottom:40},eyebrow:{fontWeight:"900",fontSize:12,letterSpacing:1.2,color:"#2563eb"},heading:{fontSize:28,fontWeight:"900",color:"#0f172a"},muted:{color:"#64748b",lineHeight:20},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:18,padding:16,gap:13},cardTitle:{fontSize:17,fontWeight:"900",color:"#0f172a"},label:{fontSize:12,fontWeight:"800",color:"#475569"},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:11,padding:11,backgroundColor:"#fff",color:"#0f172a"},two:{flexDirection:"row",gap:10},line:{paddingVertical:10,gap:10,borderBottomWidth:1,borderBottomColor:"#e2e8f0"},lineTitle:{fontWeight:"900",color:"#0f172a"},chips:{gap:7,paddingVertical:2},chip:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:99,paddingHorizontal:11,paddingVertical:8},chipOn:{backgroundColor:"#dbeafe",borderColor:"#60a5fa"},chipText:{fontSize:12,fontWeight:"700",color:"#475569"},chipTextOn:{color:"#1d4ed8"},fileRow:{gap:7},fileActions:{flexDirection:"row",gap:8,flexWrap:"wrap"},fileButton:{borderWidth:1,borderColor:"#bfdbfe",backgroundColor:"#eff6ff",borderRadius:11,padding:10},fileButtonText:{color:"#1d4ed8",fontWeight:"800"},remove:{color:"#be123c",fontWeight:"800",paddingVertical:6},add:{alignItems:"center",borderWidth:1,borderStyle:"dashed",borderColor:"#94a3b8",borderRadius:11,padding:12},addText:{fontWeight:"900",color:"#475569"},total:{flexDirection:"row",justifyContent:"space-between",padding:16,backgroundColor:"#0f172a",borderRadius:16},totalLabel:{color:"#cbd5e1",fontWeight:"800"},totalValue:{color:"#fff",fontWeight:"900",fontSize:20},actions:{flexDirection:"row",gap:10},button:{flex:1,alignItems:"center",padding:14,borderRadius:13},secondary:{backgroundColor:"#fff",borderWidth:1,borderColor:"#cbd5e1"},secondaryText:{fontWeight:"900",color:"#334155"},primary:{backgroundColor:"#2563eb"},primaryText:{fontWeight:"900",color:"#fff"}});
